checkpoint: ${oc.env:GENALM_HOME}/models/model_010726/pytorch_model.bin
genome_fasta: ${oc.env:GENALM_HOME}/data/genomes/hg38/hg38.fa
description_json: data/descriptions/ENCFF556YQA.json
mutation_window_bp: 1000
score_window_bp: 500
