model_kwargs:
  _target_: builtins.dict
  hf: true
  hf_model_name: ${oc.env:CAGI5_MODEL_ROOT}/modernbert_large
  hf_model_name_decoder: ${oc.env:CAGI5_MODEL_ROOT}/decoder
  desc_model_name: Qwen/Qwen3-Embedding-0.6B
  loss_fct:
    _target_: torch.nn.MSELoss
    reduction: none
  activation:
    _target_: torch.nn.Identity
  config:
    _target_: builtins.dict
  weight: 8
