TASK_NAME: expression/fixed_loss_test_final_bs256_lr1e5_nkeys14_shuffle_all_dropout_dp01
HOME_PATH: ${oc.env:GENALM_HOME}

MODEL_PATH_ROOT: ${HOME_PATH}/runs/${TASK_NAME}


args_params:

  _target_: builtins.dict
  
  # init_checkpoint: "/home/jovyan/shares/SR003.nfs2/aspeedok/runs/expression/loss_test_baseline_bs210/20260218-025532/model_3000/pytorch_model.bin"

  resume: #"/20251127-022624/model_25000/pytorch_model.bin" 

  model_cfg: "./data/configs/L12-H768-A12-V32k-preln.json"

  model_cls: "downstream_tasks.expression_prediction.expression_model_final_all_dropout:ExpressionCounts"

  model_path: ${MODEL_PATH_ROOT}

  clip_grad_norm: 1

  input_seq_len: 1024

  optimizer: "AdamW"

  weight_decay: 1e-4

  seed: 45

  num_warmup_steps: 10000

  log_interval: 20

  valid_interval: 20

  save_best: True

  save_interval: 1000

  optimize_metric: "score_predictions_Expression_dataset_v1_GRCh38_csv dataset"

  optimize_mode: "max"

  data_n_workers: 7

  lr: 1e-5

  lr_scheduler: "constant_with_warmup"

  reset_lr: True

  reset_optimizer: True

  reset_iteration: True

  early_stopping_patience: 500000

  iters: 350000

  gen_tokenizer: "AIRI-Institute/gena-lm-bert-base-t2t"

  text_tokenizer: "Qwen/Qwen3-Embedding-0.6B"

 # save_predictions: True

selected_targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ct_specific_benchmark/selected_targets.csv"

model_kwargs:
  _target_: builtins.dict 
  hf: True
  hf_model_name: "${HOME_PATH}/models/modernbert_large"
  hf_model_name_decoder: "${HOME_PATH}/models/decoderdp0.1"
  desc_model_name: "Qwen/Qwen3-Embedding-0.6B"
  dropout_prob: 0.1
  
  loss_fct:
    _target_: torch.nn.MSELoss
    reduction: 'none'

  activation:
    _target_:  downstream_tasks.expression_prediction.expression_model_final_all_dropout.ExpActivation

  config:
    _target_: builtins.dict

# shared dataset parameters
shared_dataset_params:
  gen_tokenizer: ${args_params.gen_tokenizer}
  gen_max_seq_len: ${args_params.input_seq_len}
  text_tokenizer: ${args_params.text_tokenizer}
  text_max_seq_len: 510
  n_keys: 14
  loglevel: 
    "_target_": "logging.getLevelName"
    "level": "DEBUG"
  seed: "${args_params.seed}"

#train
train_dataset_human_borzoi_v1:

  _target_: downstream_tasks.expression_prediction.expression_dataset_final_shufflenkeys.ExpressionDataset

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.forward.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.reverse.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_borzoi_and_v1_human.csv"
  
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa"

  tpm: csv
  num_before: 512 
  transform_targets_tpm:   
    _target_: downstream_tasks.expression_prediction.expression_dataset_final_shufflenkeys.logtransform        
    pseudocount: 1

train_dataset_mouse_full_borzoi:

  _target_: downstream_tasks.expression_prediction.expression_dataset_final_shufflenkeys.ExpressionDataset

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.train.forward.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.train.reverse.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_borzoi_mouse_qnorm.csv"
 
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm10/mm10.fa"

  tpm: csv
  num_before: 512 
  transform_targets_tpm:   
    _target_: downstream_tasks.expression_prediction.expression_dataset_final_shufflenkeys.logtransform        
    pseudocount: 1


#valid
valid_dataset_human:
  _target_: downstream_tasks.expression_prediction.expression_dataset_final_shufflenkeys.ExpressionDataset
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.valid.forward.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.valid.reverse.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_csv_file_mappings_qnorm.csv" 
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa" 
  tpm: csv
  num_before: 512 
  transform_targets_tpm:   
    _target_: downstream_tasks.expression_prediction.expression_dataset_final_shufflenkeys.logtransform        
    pseudocount: 1
