; for cpt in data/mgena_cpts/base/*.pt; do n=$(basename $cpt | cut -d "-" -f1-2); echo $n; CUDA_VISIBLE_DEVICES=1; python compute_entropy.py --config configs/modgena-generic.ini --name modgena-base-$n --cpt_path $cpt; done
; for cpt in data/mgena_cpts/large/*.pt; do n=$(basename $cpt | cut -d "-" -f1-2); echo $n; CUDA_VISIBLE_DEVICES=1; python compute_entropy.py --config configs/modgena-generic.ini --name modgena-large-$n --cpt_path $cpt; done
; for cpt in data/mgena_cpts/xlarge/*.pt; do n=$(basename $cpt | cut -d "-" -f1-2); echo $n; CUDA_VISIBLE_DEVICES=1; python compute_entropy.py --config configs/modgena-generic.ini --name modgena-xlarge-$n --cpt_path $cpt; done

[DEFAULT]
; name = modgena-base-ep30-ba90700

model_family = ModernGENA
; cpt_path = data/mgena_cpts/moderngena-base-pretrain-promoters_multi_v2-ep30-ba90700/ep30-ba90700-rank0.pt
input_len_tokens = 1024
tokenizer_path = AIRI-Institute/gena-lm-bert-base-t2t
modernbert_distr_path = /disk/10tb/home/fishman/DNALM/

genome_path = data/hg38.gapless.fa
chrm = chr21
batch_size = 2
out_dir = data/
masking_fraction = 0.12