from torch.utils.data import Dataset
import pandas as pd
import numpy as np


class DeepSeaDataset(Dataset):
    def __init__(self, datapath: str, tokenizer, max_seq_len: int = 512):
        self.data = pd.read_csv(datapath, sep=',', header=None, dtype={i: np.int8 for i in range(1, 920)})
        self.data['targets'] = list(self.data.iloc[:, 1:].values)
        self.data = self.data[[0, 'targets']]
        self.data.columns = ['seq', 'targets']

        self.max_seq_len = max_seq_len
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample = self.data['seq'][idx]
        targets = self.data['targets'][idx]

        features = self.tokenizer(sample, add_special_tokens=True, padding='max_length', truncation='longest_first',
                                  max_length=self.max_seq_len, return_tensors='np')
        # return features generated by tokenizer and labels
        for fn in features:
            features[fn] = features[fn][0]
        features['labels'] = targets.astype(np.float32)
        return features
