shared_dataset_params:
  num_before: 250
  gen_tokenizer: AIRI-Institute/gena-lm-bert-base-t2t
  gen_max_seq_len: "${args_params.input_seq_len}"
  loglevel:
    _target_: logging.getLevelName
    level: DEBUG
  transform_targets_bw:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform
    pseudocount: 1
  transform_targets_tpm:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform
    pseudocount: 1
  seed: "${args_params.seed}"

train_dataset_random_borzoi_GCF_000001405.40:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000001405.40/GCF_000001405.40.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_000001405.40.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001405.40/GCF_000001405.40.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001405.40/GCF_000001405.40.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_000001405.40:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000001405.40/GCF_000001405.40.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_000001405.40.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001405.40/GCF_000001405.40.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001405.40/GCF_000001405.40.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_000001635.27:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000001635.27/GCF_000001635.27.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_000001635.27.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001635.27/GCF_000001635.27.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001635.27/GCF_000001635.27.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_000001635.27:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000001635.27/GCF_000001635.27.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_000001635.27.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001635.27/GCF_000001635.27.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000001635.27/GCF_000001635.27.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_000003025.6:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000003025.6/GCF_000003025.6.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_000003025.6.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000003025.6/GCF_000003025.6.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000003025.6/GCF_000003025.6.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_000003025.6:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000003025.6/GCF_000003025.6.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_000003025.6.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000003025.6/GCF_000003025.6.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000003025.6/GCF_000003025.6.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_002263795.3:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_002263795.3/GCF_002263795.3.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_002263795.3.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_002263795.3/GCF_002263795.3.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_002263795.3/GCF_002263795.3.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_002263795.3:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_002263795.3/GCF_002263795.3.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_002263795.3.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_002263795.3/GCF_002263795.3.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_002263795.3/GCF_002263795.3.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_011100685.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_011100685.1/GCF_011100685.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_011100685.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_011100685.1/GCF_011100685.1.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_011100685.1/GCF_011100685.1.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_011100685.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_011100685.1/GCF_011100685.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_011100685.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_011100685.1/GCF_011100685.1.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_011100685.1/GCF_011100685.1.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_016772045.2:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_016772045.2/GCF_016772045.2.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_016772045.2.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_016772045.2/GCF_016772045.2.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_016772045.2/GCF_016772045.2.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_016772045.2:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_016772045.2/GCF_016772045.2.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_016772045.2.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_016772045.2/GCF_016772045.2.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_016772045.2/GCF_016772045.2.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_036323735.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_036323735.1/GCF_036323735.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_036323735.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_036323735.1/GCF_036323735.1.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_036323735.1/GCF_036323735.1.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_036323735.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_036323735.1/GCF_036323735.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_036323735.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_036323735.1/GCF_036323735.1.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_036323735.1/GCF_036323735.1.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_041296265.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_041296265.1/GCF_041296265.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_041296265.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_041296265.1/GCF_041296265.1.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_041296265.1/GCF_041296265.1.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_041296265.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_041296265.1/GCF_041296265.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_041296265.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_041296265.1/GCF_041296265.1.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_041296265.1/GCF_041296265.1.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_049350105.2:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_049350105.2/GCF_049350105.2.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_049350105.2.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_049350105.2/GCF_049350105.2.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_049350105.2/GCF_049350105.2.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_049350105.2:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_049350105.2/GCF_049350105.2.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_049350105.2.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_049350105.2/GCF_049350105.2.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_049350105.2/GCF_049350105.2.test.reverse.tsv"
  tpm: tpm

train_dataset_random_borzoi_GCF_964237555.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_964237555.1/GCF_964237555.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_964237555.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_964237555.1/GCF_964237555.1.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_964237555.1/GCF_964237555.1.train.reverse.tsv"
  tpm: tpm

test_dataset_random_borzoi_GCF_964237555.1:
  _target_: downstream_tasks.expression_prediction.expression_dataset_cells.ExpressionDataset
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_964237555.1/GCF_964237555.1.fa"
  targets_path: /beegfs/scratch/ws/ws1/tsoies-Expression/GENA_LM/downstream_tasks/expression_prediction/intervals_full/random_borzoi/file_mappings/random_borzoi_GCF_964237555.1.csv
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/file_mappings_embeddings.pkl"
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_964237555.1/GCF_964237555.1.test.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_964237555.1/GCF_964237555.1.test.reverse.tsv"
  tpm: tpm
