TASK_NAME: expression/qnorm/qnorm_v1_mouse_large_ATAC_seq_3_dataset

HOME_PATH: ${oc.env:GENALM_HOME}

MODEL_PATH_ROOT: ${HOME_PATH}/runs/${TASK_NAME}


args_params:

  _target_: builtins.dict
  
  # init_checkpoint: "/workspace-SR003.nfs2/aspeedok/runs/expression/qnorm/qnorm_v1_mouse_large_2seg/20250820-151948/model_best/pytorch_model.bin"

  resume: #"20250811-155853/model_best.pth"

  model_cfg: "./data/configs/L12-H768-A12-V32k-preln.json"

  backbone_cls: "downstream_tasks.expression_prediction.expression_model:ExpressionCounts"

  backbone_trainable: True

  model_cls: "src.gena_lm.modeling_rmt:RMTEncoderExpression"

  model_path: ${MODEL_PATH_ROOT}

  clip_grad_norm: 1

  input_seq_len: 504
  
  input_size: 512  
  
  num_mem_tokens: 5

  mixed_length_ratio: 0.0
  
  max_n_segments: 1

  bptt_depth: -1 

  optimizer: "AdamW"

  weight_decay: 1e-4

  seed: 43

  num_warmup_steps: 1000

  log_interval: 50

  valid_interval: 50

  save_best: True

  save_interval: 5000

  optimize_metric: "score_predictions_Expression_dataset_v1_mm10_CPM dataset"

  optimize_mode: "max"

  data_n_workers: 7

  lr: 3e-05

  lr_scheduler: "constant_with_warmup"

  reset_lr: True

  reset_optimizer: True

  reset_iteration: True

  early_stopping_patience: 50000

  iters: 350000

  gen_tokenizer: "AIRI-Institute/gena-lm-bert-base-t2t"

 # save_predictions: True
  

selected_targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ct_specific_benchmark/selected_targets.csv"


model_kwargs:

  _target_: builtins.dict
  
  hf: True

  hf_model_name: "AIRI-Institute/gena-lm-bert-large-t2t"

  loss_fct:

    _target_: torch.nn.MSELoss

    reduction: 'none'


  activation:

    _target_: torch.nn.Identity

  config:

    _target_: builtins.dict
    
  weight: 5

shared_dataset_params:
  _target_: downstream_tasks.expression_prediction.expression_dataset.ExpressionDataset
  gen_tokenizer: "AIRI-Institute/gena-lm-bert-base-t2t"
  gen_max_seq_len: ${args_params.input_seq_len}
  loglevel: 
    "_target_": "logging.getLevelName"
    "level": "DEBUG"

    
  seed: ${args_params.seed}
  fraction_of_cell_type_specific_tpm_samples: 0
  # cell_type_specific_samples_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/tpm/cell_type_specific_samples_log_pk1_z-3..3.csv"



train_dataset_mouse:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.train.forward.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.train.reverse.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_CPM_file_mappings_qnorm.csv"
  
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm10/mm10.fa"

  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/full_combined_file_mappings_embeddings.pkl"
  
  tpm: CPM

  num_before: 250

  transform_targets_tpm:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform    
    pseudocount: 1
    
  
train_dataset_ATAC_mouse:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse_mm39.train.cre.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse_mm39.train.reverse.cre.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ATACseq_Egor/file_mappings_qnorm.csv"

  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ATACseq_Egor/file_mappings_qnorm_embeddings.pkl"

  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm39/mm39.fa"
  
  bw: bw

  num_before: 0

  transform_targets_bw:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform
    pseudocount: 1

train_dataset_ATAC_human_1:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.cre.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.reverse.cre.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ATACseq_Egor_Human/file_mappings_qnorm.csv" 

  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ATACseq_Egor_Human/file_mappings_qnorm_embeddings.pkl"

  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa"
  
  bw: bw

  num_before: 0

  transform_targets_bw:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform
    pseudocount: 1
  
train_dataset_ATAC_human_2:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.cre.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.reverse.cre.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/Lai_et_al_ATAC_minja/file_mappings_qnorm.csv"

  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/Lai_et_al_ATAC_minja/file_mappings_qnorm_embeddings.pkl"

  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa"
  
  bw: bw

  num_before: 0

  transform_targets_bw:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform
    pseudocount: 1

valid_dataset_mouse:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.valid.forward.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.valid.reverse.csv"

  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_CPM_file_mappings_qnorm.csv"
  
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm10/mm10.fa"

  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/full_combined_file_mappings_embeddings.pkl"
  
  tpm: CPM
  
  num_before: 250

  transform_targets_tpm:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform    
    pseudocount: 1


