TASK_NAME: expression/description/e5

HOME_PATH: ${oc.env:GENALM_HOME}

MODEL_PATH_ROOT: ${HOME_PATH}/runs/${TASK_NAME}


args_params:

  _target_: builtins.dict
  
  # init_checkpoint: "/workspace-SR003.nfs2/aspeedok/runs/expression/qnorm/qnorm_v1_mouse_large_2seg/20250820-151948/model_best/pytorch_model.bin"

  resume: #"/20251127-022624/model_30000/pytorch_model.bin"

  model_cfg: "./data/configs/L12-H768-A12-V32k-preln.json"

  backbone_cls: "downstream_tasks.expression_prediction.expression_model_description:ExpressionCounts"

  backbone_trainable: True

  model_cls: "src.gena_lm.modeling_rmt:RMTEncoderExpression_description"

  model_path: ${MODEL_PATH_ROOT}

  clip_grad_norm: 1

  input_seq_len: 504
  
  input_size: 512  
  
  num_mem_tokens: 5

  mixed_length_ratio: 0.0
  
  max_n_segments: 1

  bptt_depth: -1 

  optimizer: "AdamW"

  weight_decay: 1e-4

  seed: 45

  num_warmup_steps: 5000

  log_interval: 100

  valid_interval: 100

  save_best: True

  save_interval: 5000

  optimize_metric: "score_predictions_Expression_dataset_v1_mm10_CPM dataset"

  optimize_mode: "max"

  data_n_workers: 7

  lr: 1e-4

  lr_scheduler: "constant_with_warmup"

  reset_lr: True

  reset_optimizer: True

  reset_iteration: True

  early_stopping_patience: 500000

  iters: 350000

  gen_tokenizer: "AIRI-Institute/gena-lm-bert-base-t2t"

  text_tokenizer: "intfloat/multilingual-e5-large-instruct"

 # save_predictions: True
  

selected_targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ct_specific_benchmark/selected_targets.csv"


model_kwargs:

  _target_: builtins.dict
  
  hf: True

  hf_model_name: "AIRI-Institute/gena-lm-bert-large-t2t"

  desc_model_name: "intfloat/multilingual-e5-large-instruct"
  

  loss_fct:

    _target_: torch.nn.MSELoss

    reduction: 'none'


  activation:

    _target_: torch.nn.Identity

  config:

    _target_: builtins.dict

  weight: 5

# shared dataset parameters
shared_dataset_params:
  _target_: downstream_tasks.expression_prediction.expression_dataset_description.ExpressionDataset
  gen_tokenizer: ${args_params.gen_tokenizer}
  gen_max_seq_len: ${args_params.input_seq_len}
  loglevel: 
    "_target_": "logging.getLevelName"
    "level": "DEBUG"
  seed: ${args_params.seed}
  text_tokenizer: ${args_params.text_tokenizer}
  text_max_seq_len: 512

train_dataset_mouse:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.train.forward.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.train.reverse.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_CPM_file_mappings_qnorm.csv" 
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm10/mm10.fa" 
  tpm: CPM
  num_before: 250
  transform_targets_tpm:   
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform       
    pseudocount: 1


train_dataset_human:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.forward.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.reverse.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_csv_file_mappings_qnorm.csv"  
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa"  
  tpm: csv
  num_before: 250 
  transform_targets_tpm:    
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform        
    pseudocount: 1

train_dataset_multi_species_rna_geo_artem_GCF_000317375.1_tpm_bw:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000317375.1/GCF_000317375.1.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_000317375.1/GCF_000317375.1.train.reverse.tsv"
  targets_path: ${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/multi_species_rna_geo_artem/file_mappings_multi_species_rna_geo_artem_description/multi_species_rna_geo_artem_GCF_000317375.1_tpm_bw.csv
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_000317375.1/GCF_000317375.1.fa"
  tpm: tpm
  num_before: 250 
  transform_targets_tpm:    
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform        
    pseudocount: 1

train_dataset_multi_species_rna_geo_artem_GCF_037993035.2_tpm_bw:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_037993035.2/GCF_037993035.2.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_037993035.2/GCF_037993035.2.train.reverse.tsv"
  targets_path: ${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/multi_species_rna_geo_artem/file_mappings_multi_species_rna_geo_artem_description/multi_species_rna_geo_artem_GCF_037993035.2_tpm_bw.csv
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_037993035.2/GCF_037993035.2.fa"
  tpm: tpm
  num_before: 250 
  transform_targets_tpm:    
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform        
    pseudocount: 1

train_dataset_multi_species_rna_geo_artem_GCF_002263795.3_tpm_bw:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_002263795.3/GCF_002263795.3.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_002263795.3/GCF_002263795.3.train.reverse.tsv"
  targets_path: ${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/multi_species_rna_geo_artem/file_mappings_multi_species_rna_geo_artem_description/multi_species_rna_geo_artem_GCF_002263795.3_tpm_bw.csv
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_002263795.3/GCF_002263795.3.fa"
  tpm: tpm
  num_before: 250 
  transform_targets_tpm:    
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform        
    pseudocount: 1

train_dataset_multi_species_rna_geo_artem_GCF_036323735.1_tpm_bw:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_036323735.1/GCF_036323735.1.train.forward.tsv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/GCF_036323735.1/GCF_036323735.1.train.reverse.tsv"
  targets_path: ${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/multi_species_rna_geo_artem/file_mappings_multi_species_rna_geo_artem_description/multi_species_rna_geo_artem_GCF_036323735.1_tpm_bw.csv
  tpm: tpm
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/GCF_036323735.1/GCF_036323735.1.fa"
  num_before: 250 
  transform_targets_tpm:    
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform        
    pseudocount: 1

train_dataset_ATAC_mouse:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse_mm39.train.cre.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse_mm39.train.reverse.cre.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ATACseq_Egor/file_mappings_qnorm_description.csv"
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm39/mm39.fa" 
  bw: bw
  num_before: 0
  transform_targets_bw:    
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform    
    pseudocount: 1

  
train_dataset_ATAC_human_2:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.cre.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.reverse.cre.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/Lai_et_al_ATAC_minja/file_mappings_qnorm.csv"
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa" 
  bw: bw
  num_before: 0
  transform_targets_bw:   
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform   
    pseudocount: 1


valid_dataset_mouse:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.valid.forward.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/mouse.valid.reverse.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_CPM_file_mappings_qnorm.csv" 
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/mm10/mm10.fa" 
  tpm: CPM
  num_before: 250
  transform_targets_tpm: 
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform      
    pseudocount: 1


valid_dataset_human:
  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.valid.forward.csv"
  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.valid.reverse.csv"
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_csv_file_mappings_qnorm.csv" 
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa" 
  tpm: csv
  num_before: 250 
  transform_targets_tpm:   
    _target_: downstream_tasks.expression_prediction.expression_dataset_description.logtransform        
    pseudocount: 1

