TASK_NAME: expression/qnorm/qnorm_v1_large_1seg_human_bw_norm

HOME_PATH: ${oc.env:GENALM_HOME}

MODEL_PATH_ROOT: ${HOME_PATH}/runs/${TASK_NAME}


args_params:

  _target_: builtins.dict
  
  # init_checkpoint:  "/workspace-SR003.nfs2/aspeedok/runs/expression/qnorm/qnorm_v1_large_1seg_human/resume_20250818-155449/model_best/pytorch_model.bin/20250819-001254/model_best/pytorch_model.bin"

  resume: #"resume_20250818-155449/model_best/pytorch_model.bin/20250819-001254/model_best/pytorch_model.bin"

  model_cfg: "./data/configs/L12-H768-A12-V32k-preln.json"

  backbone_cls: "downstream_tasks.expression_prediction.expression_model:ExpressionCounts"

  backbone_trainable: True

  model_cls: "src.gena_lm.modeling_rmt:RMTEncoderExpression"

  model_path: ${MODEL_PATH_ROOT}

  clip_grad_norm: 1

  input_seq_len: 504
  
  input_size: 512  
  
  num_mem_tokens: 5

  mixed_length_ratio: 0.0
  
  max_n_segments: 1

  bptt_depth: -1 

  optimizer: "AdamW"

  weight_decay: 1e-4

  seed: 43

  num_warmup_steps: 4000

  log_interval: 20

  valid_interval: 20

  save_best: True

  save_interval: 5000

  optimize_metric: "score_predictions_Expression_dataset_v1_GRCh38_csv dataset"

  optimize_mode: "max"

  data_n_workers: 10

  lr: 3e-05

  lr_scheduler: "constant_with_warmup"

  reset_lr: True

  reset_optimizer: True

  reset_iteration: True

  early_stopping_patience: 50000

  iters: 350000

  gen_tokenizer: "AIRI-Institute/gena-lm-bert-base-t2t"
  
  save_predictions: True
  

selected_targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/ct_specific_benchmark/selected_targets.csv"


model_kwargs:

  _target_: builtins.dict
  
  hf: True

  hf_model_name: "AIRI-Institute/gena-lm-bert-large-t2t"

  loss_fct:

    # _target_: "downstream_tasks.expression_prediction.expression_model.QuantileLoss"

    # reduction: 'none'

    # quantile: 0.9

    _target_: torch.nn.MSELoss

    reduction: 'none'

  activation:

    _target_: torch.nn.Identity

  config:

    _target_: builtins.dict

  weight: 100
  # cell_type_specific_loss_fn:
  #   _target_: downstream_tasks.expression_prediction.expression_model.cell_type_specific_loss_fn
  #   weight_mean: 0.1

  

# shared dataset parameters
shared_dataset_params:
  _target_: downstream_tasks.expression_prediction.expression_dataset.ExpressionDataset
  num_before: 250
  gen_tokenizer: "AIRI-Institute/gena-lm-bert-base-t2t"
  gen_max_seq_len: ${args_params.input_seq_len}
  targets_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/Expression_dataset_v1_csv_file_mappings_qnorm.csv"
  genome: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/genomes/hg38/hg38.fa" 
  tpm: csv
  bw: bw
  norm_bw: True
  text_data_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/file_mappings/full_combined_file_mappings_embeddings.pkl"
  loglevel: 
    "_target_": "logging.getLevelName"
    "level": "DEBUG"
  transform_targets_bw:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform
    pseudocount: 1

  transform_targets_tpm:
    _target_: downstream_tasks.expression_prediction.expression_dataset.logtransform    
    pseudocount: 1
    
  seed: ${args_params.seed}
  fraction_of_cell_type_specific_tpm_samples: 0
  # cell_type_specific_samples_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/datasets/data/tpm/cell_type_specific_samples_log_pk1_z-3..3.csv"

train_dataset_human:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.forward.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.train.reverse.csv"

  
valid_dataset_human:

  forward_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.valid.forward.csv"

  reverse_intervals_path: "${HOME_PATH}/GENA_LM/downstream_tasks/expression_prediction/intervals/human.valid.reverse.csv"
  

